public class MembershipConstants {
    public static final String STANDARD = 'Standard';
    public static final String NOSTAFF = 'no staff';
    public static final String INSUFFICIENT_ACCESS = 'Insufficient access';
    public static final String DUPLICATE_RECORDS_FOUND = 'Duplicate records found.';
    public static final String NONE = 'none';
    public static final String PARENT ='Parent';
    public static final String COMPANION = 'Companion';
    public static final String JOINT = 'joint';
    public static final String INDIVIDUAL = 'Individual';
    public static final String CREDIT_OR_DEBIT_CARD ='Credit/Debit Card';
    public static final String TRUE_VALUE ='true'; 
    public static final String PENDING = 'Pending';
    public static final String TEST = 'Test';
    public static final String BANK_ACCOUNT ='Bank Account';
    public static final String CONFIRMED ='Confirmed';
    public static final String ONLINE_MEMBERSHIP_APPLICATION = 'Online Membership Application';
    public static final String SALESFORCE = 'Salesforce';
    public static final String LIFEMEMBERSHIP = 'Life Membership - Free';
    public static final String STAFF = 'staff';
    public static final String CANCELLED = 'Cancelled';
    public static final String LAPSED = 'Lapsed';
    public static final String REPLACE = 'replace';
    public static final String CREDITCARD = 'CreditCard';
    public static final String PAYMENTHUB = 'PaymentHub';
    
}